substitutions:
  name: "everything-presence-lite"
  friendly_name: "Everything Presence Lite"
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: ERROR

wifi:
  on_connect:
    - switch.turn_on: mmwave_sensor

update:
  - platform: http_request
    id: update_http_request
    name: Everything Presence Lite Firmware
    source: https://everythingsmarthome.github.io/everything-presence-lite/everything-presence-lite-ha-sen0395-no-ble-manifest.json
    disabled_by_default: true

dashboard_import:
  package_import_url: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-sen0395-no-ble.yaml@main
  import_full_config: false # or true

packages:
  device_base: !include common/everything-presence-lite-base.yaml
  ld2450_base: !include common/sen0395-base.yaml
  co2_base: !include common/modules/co2.yaml