api:
  services:
    - service: calibrate_co2_value
      variables:
        co2_ppm: int
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda "return co2_ppm;"
            id: scd40
    - action: set_ambient_pressure
      variables:
        pressure_mbar: int
      then:
        - lambda: "id(scd40)->set_ambient_pressure_compensation(pressure_mbar);"             

i2c:
  - id: bus_b
    sda: 26
    scl: 27
    scan: true

sensor:
  - platform: scd4x
    i2c_id: bus_b
    id: scd40
    co2:
      name: "CO2"
      id: "co2"
      filters:
        - or:
          - delta: 5%
          - delta: 5      
    automatic_self_calibration: false

button:
    - platform: template
      name: "Calibrate CO2"
      id: calibrate_scd40
      on_press:
        - scd4x.perform_forced_calibration:
            value: 419
            id: scd40
