esphome:
  name: ${name}
  comment: Everything Presence Lite
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project: 
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.4.2"
  on_boot:
    priority: -100
    then:
      - lambda: |-
          if (std::string("${ device_config.bluetooth_enabled | lower }") == "true") {
            id(firmware_ble).publish_state("Enabled");
          } else {
            id(firmware_ble).publish_state("Disabled");
          }

          if (std::string("${ device_config.co2_enabled | lower }") == "true") {
            id(firmware_co2).publish_state("Enabled");
          } else {
            id(firmware_co2).publish_state("Disabled");
          }

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:
  actions:
    - action: set_update_manifest
      variables:
        url: string
      then:
        - lambda: |-
            ESP_LOGI("fw", "Setting update manifest URL: %s", url.c_str());
            id(update_http_request).set_source_url(url);
        - component.update: update_http_request
        - delay: 1s
        - update.perform:
            id: update_http_request
            force_update: true
    - action: get_build_flags
      then:
        - api.respond:
            data: !lambda |-
              root["ethernet_enabled"]  = ${ device_config.ethernet_enabled | lower };
              root["co2_enabled"]       = ${ device_config.co2_enabled | lower };
              root["bluetooth_enabled"] = ${ device_config.bluetooth_enabled | lower };
              root["board_revision"]    = "${ device_config.board_revision }";
              root["sensor_variant"]    = "${ device_config.sensor_variant }";
              root["firmware_channel"]  = "${ device_config.firmware_channel }";
              root["model"]             = "${ device_config.model }";

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:

wifi:

improv_serial:

i2c:
-  id: bus_a
   sda: 21
   scl: 22
   scan: true

light:
  - platform: status_led
    name: ESP32 LED
    id: esp32_led
    pin: GPIO14
    internal: False
    restore_mode: ALWAYS_OFF
    entity_category: config

number:
  - platform: template
    name: "Illuminance Offset"
    id: illuminance_offset_ui
    unit_of_measurement: "lx"
    min_value: -100
    max_value: 100
    step: 5
    mode: slider
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:brightness-5"
    entity_category: config
    on_value:
      - lambda: 'id(illuminance_sensor).update();'

sensor:
  - platform: bh1750
    name: Illuminance
    id: illuminance_sensor
    i2c_id: bus_a
    address: 0x23
    update_interval: ${illuminance_update_interval}
    accuracy_decimals: 0
    filters:
      - lambda: "return x + id(illuminance_offset_ui).state;"
      - or:
        - delta: 5%
        - delta: 5
      - clamp:
          min_value: 0

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: true
    id: flash_button
    internal: True
    filters:
      - delayed_on: 50ms 
    on_multi_click:
      - timing:
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for 0.2s to 3s
          - OFF for 0.1s to 2s
          - ON for at least 5s 
        then:
          - repeat: 
              count: 5
              then:
                - light.turn_on: esp32_led
                - delay: 150ms
                - light.turn_off: esp32_led
                - delay: 150ms
          - light.turn_on: esp32_led
          - button.press: factory_reset_button

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
    entity_category: config
  - platform: template
    name: "Apply Update"
    entity_category: diagnostic
    on_press:
      - logger.log: "Applying firmware update based on selected configuration"
      - lambda: |-
          std::string base_url = "https://everythingsmarthome.github.io/everything-presence-lite/everything-presence-lite-ha";
          std::string variant = "${device_config.sensor_variant}";
          if (variant == "ld2450") {
            variant.clear();
          }

          if (!variant.empty()) {
            base_url += "-";
            base_url += variant;
          }

          if (id(firmware_ble).state == "Disabled") {
            base_url += "-no-ble";
          }

          if (id(firmware_co2).state == "Enabled") {
            base_url += "-co2";
          }

          base_url += "-manifest.json";

          ESP_LOGI("firmware", "Switching to manifest: %s", base_url.c_str());
          id(update_http_request).set_source_url(base_url.c_str());
      - component.update: update_http_request
      - delay: 2s
      - update.perform:
          id: update_http_request
          force_update: true
  - platform: factory_reset
    id: "factory_reset_button"
    internal: True

select:
  - platform: template
    id: firmware_ble
    name: Bluetooth Proxy
    icon: "mdi:bluetooth"
    entity_category: diagnostic
    optimistic: true
    restore_value: true
    options:
      - "Disabled"
      - "Enabled"
    initial_option: "Disabled"

  - platform: template
    id: firmware_co2
    name: CO2 Sensor
    icon: "mdi:molecule-co2"
    entity_category: diagnostic
    optimistic: true
    restore_value: true
    options:
      - "Disabled"
      - "Enabled"
    initial_option: "Disabled"
