esphome:
  on_boot:
    then:
      - switch.turn_on: engineering_mode

uart:
  id: uart_bus
  baud_rate:  256000
  rx_pin: 16
  tx_pin: 17
  parity: NONE
  stop_bits: 1

ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Occupancy
    has_moving_target:
      name: Moving Target
      entity_category: diagnostic
    has_still_target:
      name: Still Target
      entity_category: diagnostic
  - platform: gpio
    pin: 18
    name: Occupancy GPIO
    device_class: Occupancy
    entity_category: diagnostic

sensor:
  - platform: ld2410
    light:
      name: mmWave Light
      disabled_by_default: true
      entity_category: diagnostic
    moving_distance:
      name: Moving Target Distance
      entity_category: diagnostic
    still_distance:
      name: Still Target Distance
      entity_category: diagnostic
    moving_energy:
      name: Moveing Target Energy
      entity_category: diagnostic
    still_energy:
      name: Still Target Energy
      entity_category: diagnostic
    detection_distance:
      name: Detection Distance
      entity_category: diagnostic
    g0:
      move_energy:
        name: Gate 0 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 0 Still Energy
        entity_category: diagnostic
    g1:
      move_energy:
        name: Gate 1 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 1 Still Energy
        entity_category: diagnostic
    g2:
      move_energy:
        name: Gate 2 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 2 Still Energy
        entity_category: diagnostic
    g3:
      move_energy:
        name: Gate 3 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 3 Still Energy
        entity_category: diagnostic
    g4:
      move_energy:
        name: Gate 4 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 4 Still Energy
        entity_category: diagnostic
    g5:
      move_energy:
        name: Gate 5 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 5 Still Energy
        entity_category: diagnostic
    g6:
      move_energy:
        name: Gate 6 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 6 Still Energy
        entity_category: diagnostic
    g7:
      move_energy:
        name: Gate 7 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 7 Still Energy
        entity_category: diagnostic
    g8:
      move_energy:
        name: Gate 8 Movement Energy
        entity_category: diagnostic
      still_energy:
        name: Gate 8 Still Energy
        entity_category: diagnostic

switch:
  - platform: ld2410
    engineering_mode:
      name: "Engineering Mode"
      id: "engineering_mode"
      entity_category: config
    bluetooth:
      name: "mmWave Bluetooth"
      disabled_by_default: true
      entity_category: config

number:
  - platform: ld2410
    timeout:
      name: Occupancy Off Delay
      entity_category: config
    light_threshold:
      name: mmWave Light Threshold
      disabled_by_default: True
      entity_category: config
    max_move_distance_gate:
      name: Max Movement Distance Gate
      entity_category: config
    max_still_distance_gate:
      name: Max Still Distance Gate
      entity_category: config
    g0:
      move_threshold:
        name: Gate 0 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 0 Still Sensitivity
        entity_category: config
    g1:
      move_threshold:
        name: Gate 1 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 1 Still Sensitivity
        entity_category: config
    g2:
      move_threshold:
        name: Gate 2 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 2 Still Sensitivity
        entity_category: config
    g3:
      move_threshold:
        name: Gate 3 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 3 Still Sensitivity
        entity_category: config
    g4:
      move_threshold:
        name: Gate 4 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 4 Still Sensitivity
        entity_category: config
    g5:
      move_threshold:
        name: Gate 5 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 5 Still Sensitivity
        entity_category: config
    g6:
      move_threshold:
        name: Gate 6 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 6 Still Sensitivity
        entity_category: config
    g7:
      move_threshold:
        name: Gate 7 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 7 Still Sensitivity
        entity_category: config
    g8:
      move_threshold:
        name: Gate 8 Movement Sensitivity
        entity_category: config
      still_threshold:
        name: Gate 8 Still Sensitivity
        entity_category: config

button:
  - platform: ld2410
    factory_reset:
      name: "Factory Reset mmWave"
      disabled_by_default: true
      entity_category: config
    restart:
      name: "Restart mmWave"
      disabled_by_default: true
      entity_category: config
    query_params:
      name: Get Values
      disabled_by_default: true
      entity_category: config

text_sensor:
  - platform: ld2410
    version:
      name: "mmWave Firmware Version"
      entity_category: diagnostic
    mac_address:
      name: "mmWave MAC Address"
      disabled_by_default: true
      entity_category: diagnostic

select:
  - platform: ld2410
    distance_resolution:
      name: "Distance Gate Resolution"
      disabled_by_default: true
      entity_category: config
    baud_rate:
      name: "mmWave Sensor Baud Rate"
      disabled_by_default: true
      entity_category: config
    light_function:
      name: mmWave Light Function
      disabled_by_default: true
      entity_category: config
    out_pin_level:
      name: GPIO Pin Level
      disabled_by_default: true
      entity_category: config
