substitutions:
  i2c_bus_a_sda_pin: "21"
  i2c_bus_a_scl_pin: "22"
  status_led_pin: "GPIO14"
  flash_button_pin: "0"
  ld2410_uart_rx_pin: "16"
  ld2410_uart_tx_pin: "17"
  ld2410_occupancy_pin: "18"
  ld2450_uart_tx_pin: "GPIO17"
  ld2450_uart_rx_pin: "GPIO16"
  mr24hpc1_uart_rx_pin: "16"
  mr24hpc1_uart_tx_pin: "17"
  sen0395_occupancy_pin: "GPIO19"
  sen0395_uart_tx_pin: "GPIO17"
  sen0395_uart_rx_pin: "GPIO16"
  sen0609_occupancy_pin: "GPIO16"
  sen0609_uart_tx_pin: "GPIO18"
  sen0609_uart_rx_pin: "GPIO17"
  co2_i2c_sda_pin: "26"
  co2_i2c_scl_pin: "27"
