esphome:
  on_boot:
    then:
      - switch.turn_on: advanced_mode

external_components:
  - source: github://limengdu/mmwave-kit-external-components@main
    refresh: 0s

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 16
  tx_pin: 17
  parity: NONE
  stop_bits: 1

seeed_mr24hpc1:
  id: my_seeed_mr24hpc1

text_sensor:
  - platform: seeed_mr24hpc1
    heart_beat:
      name: "mmWave Heartbeat"
      disabled_by_default: true
    product_model:
      name: "mmWave Model"
      disabled_by_default: true
    product_id:
      name: "mmWave Product ID"
      disabled_by_default: true
    hardware_model:
      name: "mmWave Hardware Model"
      disabled_by_default: true
    hardware_version:
      name: "mmWave Hardware Version"
      disabled_by_default: true
    keep_away:
      name: "Active Reporting Of Proximity"
    motion_status:
      name: "mmWave Motion Information"
      disabled_by_default: true
    custom_mode_end:
      name: "Custom Mode Status"

binary_sensor:
  - platform: seeed_mr24hpc1
    has_target:
      name: "Occupancy"

sensor:
  - platform: seeed_mr24hpc1
    custom_presence_of_detection:
      name: "Still Target Distance"
    movement_signs:
      name: "Movement Confidence"
    custom_motion_distance:
      name: "Moving Target Distance"
    custom_spatial_static_value:
      name: "Existence Energy"
    custom_spatial_motion_value:
      name: "Target Energy"
    custom_motion_speed:
      name: "Target Speed"
    custom_mode_num:
      name: "Current Custom Mode"

switch:
  - platform: seeed_mr24hpc1
    underly_open_function:
      name: "Advanced mode"
      id: "advanced_mode"

button:
  - platform: seeed_mr24hpc1
    restart:
      name: "Module Restart"
    custom_set_end:
      name: "Save Custom Mode Settings"

select:
  - platform: seeed_mr24hpc1
    scene_mode:
      name: "Scene"
    unman_time:
      name: "Occupancy Off Delay (Standard Function)"
      disabled_by_default: true
    existence_boundary:
      name: "Max Static Detection Distance"
    motion_boundary:
      name: "Max Distance"

number:
  - platform: seeed_mr24hpc1
    sensitivity:
      name: "Sensitivity"
    custom_mode:
      name: "Custom Mode"
    existence_threshold:
      name: "Existence Energy Threshold"
    motion_threshold:
      name: "Motion Energy Threshold"
    motion_trigger:
      name: "Occupancy On Delay"
    motion_to_rest:
      name: "Motion To Static Time"
    custom_unman_time:
      name: "Occupancy Off Delay"